'use client'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect } from 'react'

import useSWR from 'swr'
const fetcher = (...args) => fetch(...args).then(res => res.json())

function Exclusive() {
  useEffect(() => {
    const isAuthorized = async () => {
      const token = localStorage.getItem('psyart_23_token')
      !token ? (window.location.href = '/code') : null

      try {
        const res = await fetch(
          //'http://localhost:3000/api/auth/me',
          //'/api/auth/me',
          'https://tgxnikermlhtifnztllogd4guy0avfhm.lambda-url.eu-central-1.on.aws/auth/me',
          {
            headers: {
              Authorization: `Bearer ${token}`,
            },
          }
        )
        !res.ok ? (window.location.href = '/code') : null
      } catch (error) {
        console.log(error)
      }
    }
    isAuthorized()
  }, [])

  const { data, error } = useSWR(
    'https://tgxnikermlhtifnztllogd4guy0avfhm.lambda-url.eu-central-1.on.aws/image/exclusive',
    fetcher
  )

  if (error)
    return (
      <div
        className='d-flex align-items-center justify-content-center'
        style={{ height: '500px' }}
      >
        <h3>Failed to Load</h3>
      </div>
    )
  if (!data)
    return (
      <div
        className='d-flex align-items-center justify-content-center'
        style={{ height: '500px' }}
      >
        <div className='spinner-border' role='status'>
          <span className='sr-only'>Loading...</span>
        </div>
      </div>
    )

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <section id='galerija' style={{ paddingTop: '100px' }}>
        <div className='container'>
          <div className='row'>
            <div className='gallery' id='exclusive'>
              {data.map(image => {
                return (
                  <div className='mb-3' key={image.slug} id={image.slug}>
                    <a
                      href={image.name}
                      data-toggle='lightbox'
                      data-gallery='example-gallery'
                      className='col-sm-4'
                    >
                      <Image
                        className='img-fluid'
                        src={image.name}
                        width={800}
                        height={800}
                        alt='psyart 23'
                        loading='lazy'
                      />
                    </a>
                  </div>
                )
              })}
            </div>
          </div>
        </div>
      </section>
    </>
  )
}

export default Exclusive
