/* eslint-disable react/no-unescaped-entities */
import Head from 'next/head'
import Image from 'next/image'

export async function getStaticProps() {
  const res = await fetch(
    'https://tgxnikermlhtifnztllogd4guy0avfhm.lambda-url.eu-central-1.on.aws/image/general'
  )
  const data = await res.json()
  return { props: { data } }
}

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <section id='galerija' style={{ paddingTop: '80px' }}>
          {/*<!-- Grid row -->*/}
          <div className='container'>
            <div className='row'>
              {/*<!-- Grid row -->*/}
              <div className='text-center'>
                <p className='pb-5'>
                  PsyArt 23 is a monochrome photography project started in
                  Belgrade, by photograph Srdjan Kljajevic in 2022. The basic
                  idea of the project is the search for a way to express the
                  author's inner world through frotography. The love for science
                  and art combined with the basic instinct forces that drive
                  man, frozen in a moment of spacetime. The purpose of the
                  project is achieved if at least one photo from the collection
                  triggers the archetypal layers of the unconscious in the
                  viewer and evokes a deep feeling. Enjoy!
                </p>
                <p className='pb-3'>SELECTED PHOTOS</p>
              </div>
              <div className='gallery' id='gallery'>
                {data.map(image => {
                  return (
                    <div className='mb-3' key={image.slug} id={image.slug}>
                      <a
                        href={image.name}
                        data-toggle='lightbox'
                        data-gallery='example-gallery'
                        className='col-sm-4'
                      >
                        <Image
                          className='img-fluid'
                          src={image.name}
                          width={800}
                          height={800}
                          alt='psyart 23'
                          loading='lazy'
                        />
                      </a>
                    </div>
                  )
                })}
              </div>
              {/*<!-- Grid row -->*/}
            </div>
          </div>
        </section>
      </main>
    </>
  )
}
